# Generated by Django 6.0.3 on 2026-03-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Optional title for the slide', max_length=200)),
                ('image', models.ImageField(help_text='Upload slider image (recommended: 1920x1080px)', upload_to='slider_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption text', max_length=300)),
                ('display_order', models.IntegerField(default=0, help_text='Order of appearance (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide on homepage')),
                ('link_url', models.URLField(blank=True, help_text='Optional link when slide is clicked')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beneficiaries', models.IntegerField(default=0, help_text='Total number of people benefited')),
                ('completed_projects', models.IntegerField(default=0, help_text='Number of completed projects')),
                ('years_of_service', models.IntegerField(default=0, help_text='Years of service')),
                ('total_volunteers', models.IntegerField(default=0, help_text='Total active volunteers')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, help_text='Total donations received', max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Statistics',
                'verbose_name_plural': 'Site Statistics',
            },
        ),
    ]
