# Generated by Django 6.0.3 on 2026-03-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sliderimage_sitestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Physical address of the organization', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email displayed on site', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_upi_vpa',
            field=models.CharField(blank=True, help_text='UPI ID to override PAYMENT_CONFIG for donations', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text="JSON object with social media URLs, e.g. {'facebook':'...','twitter':'...'}"),
        ),
    ]
